CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Product" (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  category TEXT NOT NULL,
  imageUrl TEXT,
  sellerId INTEGER NOT NULL REFERENCES "User"(id),
  createdAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Chat" (
  id SERIAL PRIMARY KEY,
  userId INTEGER REFERENCES "User"(id),
  content TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW()
);

